# Generated by Django 4.1.2 on 2022-10-15 05:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('doj', models.DateField(default=datetime.date.today)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inv_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=100)),
                ('serial_no', models.IntegerField()),
                ('mac_id', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(choices=[('chennai', 'CHENNAI'), ('bangalore', 'BANGALORE')], default='chennai', max_length=100)),
                ('doi', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.employee')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.inventory')),
            ],
            options={
                'db_table': 'report',
            },
        ),
    ]
